module.exports = [
    "A vibrant coastal park in bustling Mumbai, showcasing lush greenery amidst skyscrapers, a sanctuary for nature lovers.",
    "A serene meadow in Delhi’s heart, offering respite from urban chaos, perfect for quiet reflection and surveys of city life.",
    "A sprawling wooded haven in tech-savvy Bangalore, blending nature with innovation, ideal for exploration and ecological surveys.",
    "A celebrated green oasis in historic Hyderabad, where modernity meets tradition, hailed for its tranquil beauty.",
    "A nurturing coastal retreat in Chennai, fostering biodiversity and peace along the Bay of Bengal’s shores.",
    "A rejuvenating riverside valley in Kolkata, awakening the senses with Hooghly’s charm and cultural echoes.",
    "A blessed scenic spot in Ahmedabad, merging Sabarmati’s calm with vibrant heritage, a peaceful urban escape.",
    "A guarded natural frontier in Pune, preserving biodiversity near the Western Ghats, a haven for conservationists.",
    "A sunlit sanctuary in Surat, where diamond city dwellers bask in nature’s embrace along the Tapi River.",
    "An elevated retreat in Jaipur, offering panoramic views of the Pink City and Aravalli hills, uplifting the spirit.",
    "A divine brookside in Lucknow, reflecting the city’s regal past, a sacred spot for quiet contemplation.",
    "A sonic oasis in Kanpur, where Ganges whispers blend with urban rhythms, immersing visitors in tranquility.",
    "A splendid urban jungle in Nagpur, the orange city, teeming with wild beauty at India’s heart.",
    "A bountiful lakeside in Vizag, yielding stunning views between hills and sea, a coastal gem.",
    "A boundary-defining retreat in Bhopal, nestled by lakes, where nature’s limits inspire introspection.",
    "A praised riverside edge in Patna, extolling Ganges’ majesty, a historic limit of urban and natural worlds.",
    "A noble green domain in Ludhiana, enriching Punjab’s industrial hub with nature’s grace and serenity.",
    "A radiant landscape in Agra, glowing with Taj’s backdrop, where history and nature shine together.",
    "A spiritual campsite in Varanasi, awakening souls along Ganges’ ghats, steeped in ancient mystique.",
    "A highland perch in Nashik, perfect for observing vineyards and Godavari’s flow, a wine city retreat.",
    "A safeguarded foothill haven in Meerut, cradling nature near the Doab, a green shield from urban sprawl.",
    "An uplifting plateau in Faridabad, rising above NCR’s bustle, offering scenic calm and elevation.",
    "A hallowed sunset spot in Ghaziabad, framing golden hues over urban skies, a sacred evening retreat.",
    "A gleaming sanctuary in Rajkot, radiating peace along Gujarat’s plains, a refuge from city life.",
    "A preserved wanderer’s delight in Vadodara, blending royal heritage with nature along Vishwamitri’s banks.",
    "A shimmering trail in Amritsar, sparkling with Golden Temple’s glow, guiding pilgrims through sacred serenity.",
    "A gentle riverside vista in Allahabad, caressing the soul where Ganges and Yamuna meet in harmony.",
    "A vibrant habitat in Ranchi, witnessing Jharkhand’s tribal roots and lush greenery in urban embrace.",
    "A bold lagoon in Jabalpur, flaunting Narmada’s beauty amid marble rocks, a natural spectacle.",
    "A joyful rural escape in Gwalior, delighting with fort views and rustic Madhya Pradesh charm.",
    "A riverside quest in Vijayawada, seeking Krishna’s flow, a serene spot in Andhra’s heart.",
    "A revered park in Jodhpur, honoring Rajasthan’s blue city with desert blooms and royal echoes.",
    "A graceful sanctuary in Madurai, preserving nature near Meenakshi’s temple, a spiritual green retreat.",
    "A warm highland embrace in Raipur, cradling Chhattisgarh’s spirit with rolling greenery and calm.",
    "A blessed wildlife haven in Kota, nurturing Rajasthan’s fauna along Chambal’s banks, a natural gift.",
    "A divine lakeside in Guwahati, deifying Brahmaputra’s edge, a sacred Assam retreat.",
    "A praised green ecosystem in Chandigarh, Le Corbusier’s planned city, blending urban and wild harmony.",
    "A revered grove in Solapur, honoring Maharashtra’s textile hub with shaded peace and earthy roots.",
    "A sandy journey in Hubli-Dharwad, imagining Karnataka’s twin cities with a dreamy coastal twist.",
    "A lush rainforest embrace in Bareilly, greening Uttar Pradesh with tropical whispers and calm.",
    "A fiery vista in Mysore, gazing at nature’s wild spark amid Karnataka’s royal splendor.",
    "A lauded campsite in Gurgaon, praising nature’s respite amid NCR’s corporate towers.",
    "A surrendered green expanse in Aligarh, yielding peace near its historic university town.",
    "A sunrise haven in Jalandhar, revered for Punjab’s golden mornings and vibrant energy.",
    "A splendid lakeside in Trichy, glowing by Cauvery’s flow, a Tamil Nadu treasure.",
    "A delightful valley in Bhubaneswar, savoring Odisha’s temple city charm and natural dips.",
    "A radiant sunny spot in Salem, shining with Tamil Nadu’s warmth and earthy allure.",
    "A blessed greenspace in Warangal, anointing Telangana’s historic city with natural sanctity.",
    "A lunar-lit retreat in Guntur, seeking Andhra’s night glow amid spice fields and calm.",
    "A tranquil haven in Bhiwandi, offering insight into Maharashtra’s textile hub with green serenity.",
    "A wild garland in Saharanpur, crowning Uttar Pradesh’s woodcraft city with untamed beauty.",
    "A hailed jungle in Gorakhpur, celebrating UP’s eastern wilds near Nepal’s border.",
    "A marvelous wildlife spot in Bikaner, showcasing Rajasthan’s desert fauna in sandy splendor.",
    "A vast prairie in Amravati, calling to Maharashtra’s heart with open fields and calm.",
    "A wandering biodome in Noida, preserving nature’s diversity amid NCR’s modern skyline.",
    "A meadow retreat in Jamshedpur, inviting visitors to Jharkhand’s steel city green lungs.",
    "A noble forest in Bhilai, enriching Chhattisgarh’s steel hub with wooded dignity.",
    "An idealized green haven in Cuttack, dreaming up Odisha’s silver city with nature’s touch.",
    "A fruitful domain in Firozabad, yielding green peace in UP’s glass city.",
    "A sonic coastal trail in Kochi, following Kerala’s backwater whispers and port charm.",
    "An enchanting preserve in Nellore, captivating Andhra’s coast with rice fields and serenity.",
    "A favored reserve in Bhavnagar, blessing Gujarat’s port city with natural respite.",
    "A painted seashore in Dehradun, imagining Uttarakhand’s valley with a dreamy coastal stroke.",
    "A revered oceanic vision in Durgapur, dreaming West Bengal’s steel city with watery grace.",
    "A praised pond in Asansol, lauding West Bengal’s coal city with reflective calm.",
    "A dynamic landscape in Rourkela, zooming into Odisha’s steel city with green vibrancy.",
    "A whimsical highland in Nanded, fancying Maharashtra’s Sikh holy city with elevated charm.",
    "A summoned preserve in Kolhapur, invoking Maharashtra’s royal past with natural sanctity.",
    "A sparkling lakeside in Ajmer, gleaming by Rajasthan’s Pushkar with desert beauty.",
    "A splendid pasture in Gulbarga, gracing Karnataka’s historic city with pastoral peace.",
    "A wandering ridge in Jamnagar, tracing Gujarat’s oil city with coastal heights.",
    "A dusk haven in Ujjain, adored for Madhya Pradesh’s temple city twilight glow.",
    "A fanciful twilight spot in Loni, dreaming UP’s edge with evening whimsy.",
    "A surveyed habitat in Siliguri, mapping West Bengal’s gateway with Darjeeling’s foothills.",
    "A sacred wildlife spot in Jhansi, ordaining UP’s historic city with natural reverence.",
    "A hallowed lake in Ulhasnagar, enshrining Maharashtra’s Sindhi hub with watery peace.",
    "A sustained scenic spot in Jammu, cradling J&K’s winter capital with Himalayan charm.",
    "A crafted habitat in Sangli, forging Maharashtra’s twin cities with green unity.",
    "A fiery enshrined spot in Mangalore, blazing Karnataka’s coast with wild energy.",
    "A rejuvenating reserve in Erode, awakening Tamil Nadu’s textile town with nature’s call.",
    "An immersive reserve in Belgaum, soaking Karnataka’s border city in green tranquility.",
    "An enchanting sunset in Ambattur, captivating Chennai’s suburb with evening magic.",
    "A surrendered zone in Tirunelveli, yielding Tamil Nadu’s south to nature’s embrace.",
    "A comprehended habitat in Malegaon, grounding Maharashtra’s textile city in natural insight.",
    "A longing forest in Gaya, yearning for Bihar’s spiritual heart with wooded peace.",
    "A crowned dusk in Jalgaon, topping Maharashtra’s banana city with twilight glory.",
    "A crafted pasture in Udaipur, forging Rajasthan’s lake city with green dreams.",
    "A holy horizon in Maheshtala, sanctifying West Bengal’s edge with skyward peace.",
    "A moonlit mourning spot in Davanagere, reflecting Karnataka’s quiet with nocturnal grace.",
    "A nurturing moonlit haven in Kozhikode, fostering Kerala’s coast with night’s glow.",
    "A discovered sunset in Akola, unveiling Maharashtra’s cotton city with evening hues.",
    "A marvelous ridge in Kurnool, tracing Andhra’s Rayalaseema with elevated wonder.",
    "A revered riverside in Bokaro, worshipping Jharkhand’s Damodar with steel city calm.",
    "A campfire haven in Bellary, awakening Karnataka’s mining town with warm nights.",
    "A blessed biotope in Patiala, enriching Punjab’s royal city with natural harmony.",
    "A highland journey in South Dumdum, tracing Bengal’s urban edge with green paths.",
    "A watery discovery in Rajahmundry, unveiling Andhra’s Godavari with serene flow.",
    "A sacred backcountry in Bhagalpur, ordaining Bihar’s silk city with rustic peace.",
    "A noble rainforest in Muzaffarpur, dignifying Bihar’s litchi hub with lush green.",
    "A meditative retreat in Bhatpara, calming West Bengal’s jute town with introspection."
]

